
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sun May 17 19:08:28 COT 2026
//----------------------------------------------------

package analizador;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int PAR_DER = 48;
  public static final int FUNCTION = 27;
  public static final int OP_REL = 52;
  public static final int MULT = 36;
  public static final int CONST = 19;
  public static final int CONCAT = 46;
  public static final int SINGLE = 25;
  public static final int ENTERO = 54;
  public static final int INPUT = 31;
  public static final int XOR = 45;
  public static final int RESTA = 35;
  public static final int DOUBLE = 22;
  public static final int INTEGER = 21;
  public static final int DOS_PUNTOS = 51;
  public static final int FOR = 7;
  public static final int IDENTIFICADOR = 53;
  public static final int NOT = 44;
  public static final int AND = 42;
  public static final int IGUAL = 41;
  public static final int ELSEIF = 5;
  public static final int OR = 43;
  public static final int CALL = 29;
  public static final int DIV = 37;
  public static final int UNTIL = 15;
  public static final int SUMA = 34;
  public static final int EOL = 57;
  public static final int NEXT = 10;
  public static final int LOOP = 14;
  public static final int EXIT = 16;
  public static final int IF = 2;
  public static final int PUNTO_COMA = 50;
  public static final int DIM = 17;
  public static final int EOF = 0;
  public static final int BOOLEAN = 24;
  public static final int DIV_ENTERA = 38;
  public static final int RETURN = 28;
  public static final int TRUE = 32;
  public static final int error = 1;
  public static final int COMA = 49;
  public static final int CADENA = 56;
  public static final int WEND = 12;
  public static final int MOD = 40;
  public static final int PAR_IZQ = 47;
  public static final int REAL = 55;
  public static final int POTENCIA = 39;
  public static final int ELSE = 4;
  public static final int TO = 8;
  public static final int WHILE = 11;
  public static final int LET = 20;
  public static final int THEN = 3;
  public static final int END = 6;
  public static final int STRING = 23;
  public static final int FALSE = 33;
  public static final int AS = 18;
  public static final int SUB = 26;
  public static final int PRINT = 30;
  public static final int DO = 13;
  public static final int STEP = 9;
}

